spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/gmail.send
              - https://www.googleapis.com/auth/gmail.metadata

          yandex:
            clientId: ${YANDEX_CLIENT_ID}
            clientSecret: ${YANDEX_CLIENT_SECRET}
            scope:
              - mail:smtp
              - login:birthday
              - login:email
              - login:info
            redirectUri: http://localhost:8080/login/oauth2/code/yandex
            responseType: token
            authorizationGrantType: authorization_code

          mailru:
            clientId: ${MAILRU_CLIENT_ID}
            clientSecret: ${MAILRU_CLIENT_SECRET}
            scope:
              - userinfo
              - mail.smtp
            redirectUri: http://localhost:8080/login/oauth2/code/mailru
            responseType: token
            authorizationGrantType: authorization_code
            prompt_force: 1

        provider:
          mailru:
            authorizationUri: https://oauth.mail.ru/login
            tokenUri: https://oauth.mail.ru/token
            userInfoUri: https://oauth.mail.ru/userinfo
            userNameAttribute: name
            userInfoAuthenticationMethod: form

          yandex:
            authorizationUri: https://oauth.yandex.ru/authorize
            tokenUri: https://oauth.yandex.ru/token
            userInfoUri: https://login.yandex.ru/info
            userNameAttribute: login

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/expertise_helper
    username: coordinator
    password: qmy8aczf
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: false

  freemarker:
    expose-request-attributes: true
    suffix: .ftl

  servlet:
    multipart:
      max-file-size: 20MB

  data:
    mongodb:
      uri: mongodb+srv://root:${MONGO_PASS}@cluster0.trtbo.mongodb.net/expertise-helper?retryWrites=true&w=majority

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

server:
  tomcat:
    max-swallow-size: 50MB

user:
  security:
    key-store-password: ${key_pass}
    key-store-name: keystore.jceks

